Template ::= @pushState(WithinContent) (Comment | Expression | Text)* ;

Comment ::= @whenState(WithinContent)
            StartComment
            @pushState(WithinComment)
            CommentContent
            EndComment
            @popState ;

StartComment ::= @token(StartComment) "{!" ;
EndComment   ::= @token(EndComment) "!}" ;

CommentContent ::= @token(CommentContent)
                   @recoverUntil("!}") ;

Expression ::= @whenState(WithinContent)
               StartExpression
               @pushState(WithinExpression)
               ExpressionContent
               EndExpression
               @popState ;

StartExpression ::= @token(StartExpression) "{_" ;
EndExpression   ::= @token(EndExpression) "}" ;

ExpressionContent ::= @token(ExpressionContent)
                     @recoverUntil("}") ;
                   
Text ::= @whenState(WithinContent) @token(Text) @recoverUntil("{") ;
